# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Ghasideh Mirzaee"
title_separator          : "-"
name                     : &name "Ghasideh Mirzaee"
description              : &description "Research in trustworthy AI, uncertainty quantification, and multimodal learning"
url                      : https://ghasideh-mirzaee.github.io
baseurl                  : ""
repository               : "ghasideh-mirzaee/Ghasideh-Mirzaee.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Ghasideh Mirzaee"
  pronouns         :
  bio              : "M.S. student in Computer Science at West Virginia University. Interested in trustworthy AI, uncertainty quantification, and multimodal learning."
  location         : "Morgantown, WV"
  employer         : "West Virginia University"
  uri              :
  email            : "Gm00071@mix.wvu.edu"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "ghasideh-mirzaee"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "ghasideh-mirzaee-699ab31a6"
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
